spring:
  profiles:
    default: local

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

    defer-datasource-initialization: true
  sql:
    init:
      mode: never # data.sql 스크립트 사용
      encoding: UTF-8

jwt:
  secretKey: ${JWT_SECRET_KEY}
  token:
    header: Authorization
    access:
      expiration: 1800000 # 30? (1000L(ms -> s) * 60L(s -> m) * 30L(m -> h))
    refresh:
      expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> ??) * 14(2?))

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

oauth:
  kakao:
    auth-url: https://kapi.kakao.com
  apple:
    auth-url: https://appleid.apple.com

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.board: DEBUG

---
spring:
  confing:
    activate:
      on-profile: "local"

---
spring:
  confing:
    activate:
      on-profile: "dev"
